In [1]:
import pandas as pd

In [2]:
data = "Resources/injuries_2010-2020.csv"

In [4]:
injuries_df = pd.read_csv(data, encoding="utf-8")
injuries_df

,Date,Team,Acquired,Relinquished,Notes
0,2010-10-03,Bulls,NaN,Carlos Boozer,fractured bone in right pinky finger (out inde...
1,2010-10-06,Pistons,NaN,Jonas Jerebko,torn right Achilles tendon (out indefinitely)
2,2010-10-06,Pistons,NaN,Terrico White,broken fifth metatarsal in right foot (out ind...
3,2010-10-08,Blazers,NaN,Jeff Ayres,torn ACL in right knee (out indefinitely)
4,2010-10-08,Nets,NaN,Troy Murphy,strained lower back (out indefinitely)
...,...,...,...,...,...
27100,2020-09-30,Lakers,Dion Waiters,NaN,activated from IL
27101,2020-10-02,Heat,NaN,Bam Adebayo,strained neck (DTD)
27102,2020-10-02,Heat,NaN,Goran Dragic,placed on IL with torn plantar fascia in left ...
27103,2020-10-02,Heat,Chris Silva,NaN,activated from IL
27104,2020-10-06,Heat,Bam Adebayo,NaN,returned to lineup

In [5]:
new_injuries_df = injuries_df[["Date", "Team", "Relinquished"]]
new_injuries_df

             Date     Team   Relinquished
0      2010-10-03    Bulls  Carlos Boozer
1      2010-10-06  Pistons  Jonas Jerebko
2      2010-10-06  Pistons  Terrico White
3      2010-10-08  Blazers     Jeff Ayres
4      2010-10-08     Nets    Troy Murphy
...           ...      ...            ...
27100  2020-09-30   Lakers            NaN
27101  2020-10-02     Heat    Bam Adebayo
27102  2020-10-02     Heat   Goran Dragic
27103  2020-10-02     Heat            NaN
27104  2020-10-06     Heat            NaN

[27105 rows x 3 columns]

In [15]:
pd.to_datetime(new_injuries_df["Date"]).dt.month

0        10
1        10
2        10
3        10
4        10
         ..
27100     9
27101    10
27102    10
27103    10
27104    10
Name: Date, Length: 27105, dtype: int64

In [13]:
new_injuries_df["Date"] = pd.to_datetime(new_injuries_df["Date"])
new_injuries_df["Year"] = new_injuries_df["Date"].dt.year
new_injuries_df

<ipython-input-13-2b635985ee65>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_injuries_df["Date"] = pd.to_datetime(new_injuries_df["Date"])
<ipython-input-13-2b635985ee65>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_injuries_df["Year"] = new_injuries_df["Date"].dt.year

            Date     Team   Relinquished  Year
0     2010-10-03    Bulls  Carlos Boozer  2010
1     2010-10-06  Pistons  Jonas Jerebko  2010
2     2010-10-06  Pistons  Terrico White  2010
3     2010-10-08  Blazers     Jeff Ayres  2010
4     2010-10-08     Nets    Troy Murphy  2010
...          ...      ...            ...   ...
27100 2020-09-30   Lakers            NaN  2020
27101 2020-10-02     Heat    Bam Adebayo  2020
27102 2020-10-02     Heat   Goran Dragic  2020
27103 2020-10-02     Heat            NaN  2020
27104 2020-10-06     Heat            NaN  2020

[27105 rows x 4 columns]

In [16]:
new_injuries_df["Date"] = pd.to_datetime(new_injuries_df["Date"])
new_injuries_df["Month"] = new_injuries_df["Date"].dt.month
new_injuries_df

<ipython-input-16-dd06c2561034>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_injuries_df["Date"] = pd.to_datetime(new_injuries_df["Date"])

            Date     Team   Relinquished  Year  Month
0     2010-10-03    Bulls  Carlos Boozer  2010     10
1     2010-10-06  Pistons  Jonas Jerebko  2010     10
2     2010-10-06  Pistons  Terrico White  2010     10
3     2010-10-08  Blazers     Jeff Ayres  2010     10
4     2010-10-08     Nets    Troy Murphy  2010     10
...          ...      ...            ...   ...    ...
27100 2020-09-30   Lakers            NaN  2020      9
27101 2020-10-02     Heat    Bam Adebayo  2020     10
27102 2020-10-02     Heat   Goran Dragic  2020     10
27103 2020-10-02     Heat            NaN  2020     10
27104 2020-10-06     Heat            NaN  2020     10

[27105 rows x 5 columns]

In [17]:
clean_injury_df = new_injuries_df.dropna(how="any")
clean_injury_df.count()

Date            17558
Team            17558
Relinquished    17558
Year            17558
Month           17558
dtype: int64

In [18]:
clean_injury_df

            Date     Team    Relinquished  Year  Month
0     2010-10-03    Bulls   Carlos Boozer  2010     10
1     2010-10-06  Pistons   Jonas Jerebko  2010     10
2     2010-10-06  Pistons   Terrico White  2010     10
3     2010-10-08  Blazers      Jeff Ayres  2010     10
4     2010-10-08     Nets     Troy Murphy  2010     10
...          ...      ...             ...   ...    ...
27097 2020-09-22  Celtics  Romeo Langford  2020      9
27098 2020-09-23     Heat    Gabe Vincent  2020      9
27099 2020-09-30     Heat     Bam Adebayo  2020      9
27101 2020-10-02     Heat     Bam Adebayo  2020     10
27102 2020-10-02     Heat    Goran Dragic  2020     10

[17558 rows x 5 columns]